let projects = [
  {
    name:"Plastic Korea",
    tags:"#wordpress, #UI/UX",
    link: "https://plastic.lifekorea.ru/",
    image:"./img/plastic.jpg",
  },
  {
    name:"LifeKorea",
    tags:"#wordpress, #fullstack, #UI/UX",
    link: "https://lifekorea.ru/",
    image:"./img/lk.png",
  },
  {
    name:"Biohacker",
    tags:"#wordpress, #fullstack, #UI/UX",
    link: "https://biohacker.bar/",
    image:"./img/pj1.png",
  },
  {
    name:"Vedicoder Blog",
    tags:"#HTML/CSS, #UI/UX, #fullstack",
    link: "https://vedicoder.fun/",
    image:"./img/vedicoder.jpg",
  },
  {
    name:"Checkup Korea",
    tags:"#HTML/CSS, #wordpress",
    link: "https://checkup.lifekorea.ru/",
    image:"./img/checkup.jpg",
  },
  {
    name:"Myongji Hospital",
    tags:"#HTML/CSS, #wordpress",
    link: "https://myongjihospital.ru/",
    image:"./img/hospital.jpg",
  },
  {
    name:"SpaceX Website",
    tags:"#HTML/CSS, #javascript",
    link: "http://spacex.tw1.ru/",
    image:"./img/SpaceX.jpg",
  },
  {
    name:"Transliterate Me",
    tags:"#HTML/CSS, #javascript",
    link: "http://transliterate.tw1.ru/",
    image:"./img/transliterate.jpg",
  },
  {
    name:"QR Generator",
    tags:"#HTML/CSS, #javascript",
    link: "http://qrgenerator.tw1.ru/",
    image:"./img/qrcode.jpg",
  },
  {
    name:"Mesto",
    tags:"#HTML/CSS, #javascript",
    link: "https://github.com/slayoffer/mesto-project",
    image:"./img/gh-logo.png",
  },
  {
    name:"Etch-A-Sketch",
    tags:"#HTML/CSS, #javascript",
    link: "https://github.com/slayoffer/etch-a-sketch",
    image:"./img/gh-logo.png",
  },
  {
    name:"How to learn",
    tags:"#HTML/CSS",
    link: "https://github.com/slayoffer/how-to-learn",
    image:"./img/gh-logo.png",
  },
  {
    name:"Russia Travel",
    tags:"#HTML/CSS",
    link: "https://github.com/slayoffer/russian-travel",
    image:"./img/gh-logo.png",
  },
  {
    name:"Drum Kit",
    tags:"#HTML/CSS, #javascript",
    link: "https://github.com/slayoffer/Drum-Kit",
    image:"./img/gh-logo.png",
  },
  {
    name:"Battle Ship",
    tags:"#HTML/CSS, #javascript",
    link: "https://github.com/slayoffer/battle-ship-game",
    image:"./img/gh-logo.png",
  },
  {
    name:"Dicee",
    tags:"#HTML/CSS, #javascript",
    link: "https://github.com/slayoffer/Dicee",
    image:"./img/gh-logo.png",
  },
]